# Generated by Django 5.0.1 on 2024-02-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('npeople', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
            },
        ),
    ]
