# Generated by Django 5.0.1 on 2024-02-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_remove_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icons',
            name='category',
            field=models.ForeignKey(max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.category'),
        ),
    ]
