# Generated by Django 5.0.1 on 2024-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_icons_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Icons',
        ),
    ]
