# Generated by Django 5.0.1 on 2024-02-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_category_icon_delete_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('message', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'csform',
                'verbose_name_plural': 'csforms',
            },
        ),
    ]
