# Generated by Django 5.0.1 on 2024-02-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_customersupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('image', models.ImageField(null=True, upload_to='employees_images')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
