# Generated by Django 5.0.1 on 2024-02-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0011_alter_booking_full_name_basket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='full_name',
            field=models.CharField(max_length=128),
        ),
    ]
