# Generated by Django 5.0.1 on 2024-02-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0012_alter_customersupport_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=128)),
                ('profession', models.CharField(blank=True, max_length=128)),
                ('image', models.ImageField(upload_to='clients_images')),
                ('review', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
